version: '3'
services:
  mongo-rs-01:
    image: mongo:4
    build: ./mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo/rs-01:/data/db
    depends_on:
      - mongo-rs-02
      - mongo-rs-03
  
  mongo-rs-02:
    image: mongo:4
    ports:
      - 27018:27017
    volumes:
      - ./mongo/rs-02:/data/db
    command: --replSet mongo-rs --smallfiles --oplogSize 128

  mongo-rs-03:
    image: mongo:4
    ports:
      - 27019:27017
    volumes:
      - ./mongo/rs-03:/data/db
    command: --replSet mongo-rs --smallfiles --oplogSize 128